redis = (loadfile "redis.lua")()
io.write("Enter Hobto ID : ")
local last = io.read()
io.write("\nEnter Full Sudo ID : ")
local sudo=io.read()
local text,ok = io.open("base.lua",'r'):read('*a'):gsub("HOBTO%-ID",last)
io.open("hobto-"..last..".lua",'w'):write(text):close()
io.open("hobto-"..last..".sh",'w'):write("while true; do\n./telegram-cli-1222 -p hobto-"..last.." -s hobto-"..last..".lua\ndone"):close()
io.popen("chmod 777 hobto-"..last..".sh")
redis:set('hobto:'..last..':fullsudo',sudo)
print("Done!\nNew Hobto Created...\nID : "..last.."\nFull Sudo : "..sudo.."\nRun : ./hobto-"..last..".sh")
